### ISSUE TITLE
Is Project Dead?

### ISSUE THREAD

**Issue by Andre0711er** [ipfs-shipyard/java-ipfs-http-client#192]
Hi. Looks like Project is dead?! Can anyone help.
Is Project alive, or is there any alternative Projects to work with?

**Comment by javaspeak** [comment]
Hi Andre,

I asked the same question.  I noticed that stuff is not working on the project just because people have not created new releases of dependent projects such as java-cid and updated the chain on poms to absorb the changes.  ie. changes were made on the master / head but a release was never made.

See:  

     https://github.com/ipfs-shipyard/java-ipfs-http-client/issues/190

Do you know how one gets permission to do releases?

I work mainly with private git repo not hosted on github so am a newby when it comes to releases on github.

I created unit tests to test all the stuff I need for this project and they all passed when I published the head version of java-cid locally.

Therefore I want to create a new release for java-cid which this project indirectly uses.  I do not know how to get privileges to to do that - do you know how I can get them? - then we can do the sh_t ourself.   Seems to me there is nice code here - just it can get out of date when new codecs are published ( like now ).

Any big picture help appreciated - I know you asked the question - but questions open up more questions :-)

Thanks

**Comment by Clay-Ferguson** [comment]
I had concluded this project was probably dead about a year ago. Here's the mess of code I concocted for my own IPFS work. (yeah I know I need to clean it up, that's why I use the word 'mess')....

https://github.com/Clay-Ferguson/quantizr/blob/master/src/main/java/quanta/service/IPFSService.java

Java is still the leading language and IPFS is the leading Web3 tech, so it's definitely a shame there's no good "Library" for this, but on the other hand it's just a RESTful service wrapper, and most REST services don't consider themselves needing to be 'wrapped'.

If anyone finds something more acceptable please post here, maybe this is where people can find it.

**Comment by Clay-Ferguson** [comment]
@rossedwardsus I don't have the time to immediately get involved, but hopefully others will see your note and help out. BTW the JS implementation of IPFS is basically crippled and can't do much. I don't know if there will ever be way to call the GOLANG directly from Java, but for now wrapping the HTTP API (of a golang gateway) seems to be the only viable option for java.

**Comment by Andre0711er** [comment]
I have integrated this IPFS Client successfully in an NFT Project. So i pimped it a little bit. Works quiet good. if you need help with that, send me a PM. Otherwise i developed a stack now in Java for NFT (Web3J, Solidity). So, IPFS was the smallest part. ;-)

**Comment by rossedwardsus** [comment]
How do i private message you?  A friend of mine and I are going to build something with NFTs for photographers.  Its mostly just a concept right now.  But we are using ethereum and of course web3j.  As you mentioned IPFS is the smallest part.  I mainly was just seeing how easy or difficult this would be and whether i could access IPFS through a library.

Java doesn't seem to be a priority in blockchain though.  So i guess its not surprising.

**Comment by Andre0711er** [comment]
Check my Profile. You will my Website, there is my E-Mail Address in Footer [Website is only in german, sorry].
Sorry, doesn't know, that Github hasn't PM inside

**Comment by Clay-Ferguson** [comment]
I'm interested as well @Andre0711er . Can we create a Matrix room for this? I don't care who owns the room, but I do know how to create one for discussing Java + Web3 + IPFS related conversations. Let me know. I'm mostly doing Fediverse work right now and already to have an ActivityPub room on Matrix. FYI. I consider that part of Web3 perhaps.

**Comment by Andre0711er** [comment]
@Clay-Ferguson Sure. I never used Matrix, but open minded for this. Will you create anything and send me a message. Otherwise we can create a short telegram group too. up to you.

**Comment by Clay-Ferguson** [comment]
I just now created this Matrix room:
 
[ipfs-java-devs](https://app.element.io/#/room/#ipfs-java-devs:matrix.org)

I'll also post it around the various forms so we can gather the Java developers interested in IPFS. Java devs please join!

**Comment by ertra** [comment]
For me, this project is working OK.
@Andre0711er pls, what is not working for you?

**Comment by Clay-Ferguson** [comment]
Abandoned projects will continue to work for a while, so I'd expect most of this code might still work, but the reason I wouldn't use it is simply because it *has* been abandoned.

**Comment by ianopolous** [comment]
The phoenix will arise soon.

**Comment by Clay-Ferguson** [comment]
Hi Ian! I'm glad someone is reviving this project! 

My project is making it's own REST calls directly to the gateway API, but it would be nicer to have this better abstraction layer to go thru.
